---
name: Build Node Docker images

on:
  workflow_dispatch:
  push:

permissions:
  actions: read
  contents: read
  id-token: write
  security-events: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          tags: zihaoyu/code-scanning-demo:v1
          load: true
      - name: Scan image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: zihaoyu/code-scanning-demo:v1
          format: 'sarif'
          output: 'trivy-results-os.sarif'
          exit-code: '0' #0 pass, 1 fail
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: '8m30s'
      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results-os.sarif'
